---
metrics_docker:
  content: |
    [plugin.metrics.docker]
    command = "/usr/bin/mackerel-plugin-docker -method API"

metrics_mysql_via_integ:
  content: |
    [plugin.metrics.mysql]
    command = ["mackerel-plugin-mysql", "-host", "{{ rds_endpoint }}", "-username", "{{ rds_user }}", "-password", "{{ rds_password }}"]
    custom_identifier = "{{ rds_endpoint }}"

metrics_aws_elasticsearch_via_integ:
  content: |
    [plugin.metrics.aws-elasticsearch]
    command = "/usr/bin/mackerel-plugin-aws-elasticsearch -domain={{ es_domain }} -client-id={{ aws_client_id }} -region={{ aws_region }} -access-key-id={{ aws_access_key }} -secret-access-key={{ aws_secret_key }}"
    custom_identifier = "{{ es_arn }}"

check_elasticsearch_connectivity:
  content: |
    [plugin.checks.elasticsearch]
    command = ["check-elasticsearch", "-s", "https", "-H", "{{ es_endpoint }}", "-p", "443"]
    custom_identifier = "{{ es_arn }}"

