---
- name: Set mackerel-agent.conf
  blockinfile:
    dest: /etc/mackerel-agent/mackerel-agent.conf
    backup: yes
    block: |
      {{ item.content }}
    marker: ""
  with_items:
    - "{{ metrics_docker }}"
    - "{{ metrics_mysql_via_integ }}"
    - "{{ metrics_aws_elasticsearch_via_integ }}"
    - "{{ check_elasticsearch_connectivity }}"
  changed_when: true
  notify: "restart mackerel-agent"