---
check_sardine:
  content: |
    [plugin.checks.check_sardine]
    command = ["go-check-plugins", "procs", "--pattern", "sardine", "-C", "1"]

check_log_speedtest:
  content: |
    [plugin.checks.check_log_speedtest_retry_1]
    command = ["go-check-plugins", "log", "--file", "/opt/sardine/speedtest-service.log", "--pattern", "#2", "-w", "2", "-c", "3", "--return"]
    check_interval = 10
    [plugin.checks.check_log_speedtest_retry_2]
    command = ["go-check-plugins", "log", "--file", "/opt/sardine/speedtest-service.log", "--pattern", "#3", "-w", "1", "-c", "2", "--return"]
    check_interval = 5
    [plugin.checks.check_log_speedtest_retry_3]
    command = ["go-check-plugins", "log", "--file", "/opt/sardine/speedtest-service.log", "--pattern", "#4", "-w", "0", "-c", "1", "--return"]
    check_interval = 2
