version: "2"

services:
  logstash:
    image: sogaoh/logstash-for-mysql-pipeline:latest
    container_name: logstash
    environment:
      - TZ=${TZ}
      - JDBC_DRIVER_FILENAME=${JDBC_DRIVER_FILENAME}
      - RDS_ENDPOINT=${RDS_ENDPOINT}
      - RDS_DATABASE=${RDS_DATABASE}
      - RDS_USERNAME=${RDS_USERNAME}
      - RDS_PASSWORD=${RDS_PASSWORD}
      - ES_ENDPOINT=${ES_ENDPOINT}
    ports:
      - 5044:5044
      - 9600:9600
